modLoader = "javafml"
loaderVersion = "[36,)"
license = "LGPLv2.1"
issueTrackerURL = "https://github.com/ErenayDev/OfflineLAN-1.16.5/issues"

[[mods]]
modId = "offlinelan"
version = "${file.jarVersion}"
displayName = "OfflineLAN 1.16.5"
authors = "ErenayDev"
description = '''
Adds extra menus to "Open to LAN" section. MOTD, Offline Mode, Port fields
'''

[[dependencies.offlinelan]]
modId = "forge"
mandatory = true
versionRange = "[36.2,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.offlinelan]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "CLIENT"
